### ISSUE TITLE
How to compute Gromov's delta-hyperbolicity?

### ISSUE THREAD

**Issue by huajianjiu** [HazyResearch/hgcn#1]
Hi!
Thank you for your amazing paper.
I am curious about Gromov's delta-hyperbolicity to measure how tree-like a graph is in your paper.
I expected to find an explanation or an implementation of it but I failed.
Could you please show me how to compute it?

**Comment by feverer** [comment]
Hi, I read your paper and I esperciall like the visualization of embedding in your job,  I expected to reproduce the result on cora, where different classes in cora can be separated well.    Could you please show me  how to  achieve that?

**Comment by ines-chami** [comment]
We added the `utils/hyperbolicity.py` script, which computes an approximation of Gromov's delta using uniform sampling. Please find an explanation of Gromov's delta [here](http://doc.sagemath.org/html/en/reference/graphs/sage/graphs/hyperbolicity.html).

**Comment by AdarshMJ** [comment]
Hi! Apologies if this question seems a little silly. In the code for calculating hyperbolicity, what does the num_samples correspond to? It is set to 50,000 by default. Does this depend on the number of nodes or edges of the graph under consideration?

Thanks in advance!
