### ISSUE TITLE
Theoretical/Motivation for why changing curvature works?

### ISSUE THREAD

**Issue by AdarshMJ** [HazyResearch/hgcn#17]
Hi, In your paper, you demonstrated the effect of curvature and the improvement of link prediction results when the curvature is decreased. I was wondering if there are any theoretical explanation for this behavior? To quantify the behavior wrt to decreasing curvature?

Thanks in advance!

**Comment by ines-chami** [comment]
Hi, we did not theoretically study the role of curvature in this paper, but our intuition is that because curvature measures how “tree-like” the embedding space is, graphs that are more “tree-like” (delta-hyperbolicity close to zero) are likely to benefit from lower negative curvature values.
