### ISSUE TITLE
Aggregation & node classification task

### ISSUE THREAD

**Issue by snooker-player** [HazyResearch/hgcn#18]
Thanks for your paper. I have two questions about this paper.
1. The code implementation of aggregation is all based on the tangent space of the origin. Could you provide the version conducted on the tangent space of each center node?
2. I'm not sure how to set the hyperparameters for the node classification task. Could you please tell me how to set them to achieve the results in the paper (especially for the Pubmed dataset).

**Comment by ines-chami** [comment]
Hi, 

1. We added the local aggregation back with the options: --use-at 1 --local-agg 1. Note that local aggregation is much slower (require computing a NxNxd matrix) and has small improvements compared to aggregation at the origin (see Table 2 in the paper). For large datasets we advise using aggregation at the origin. 
 
2. For node classification tasks, please use pertained embeddings for LP into a Shallow model. Please refer to the Readme for detailed hyperparameter configurations. 
https://github.com/HazyResearch/hgcn/blob/a526385744da25fc880f3da346e17d0fe33817f8/models/encoders.py#L146
