### ISSUE TITLE
How to reproduce  the visualization part of the paper?

### ISSUE THREAD

**Issue by feverer** [HazyResearch/hgcn#2]
Hi, I read your paper and I esperciall like the visualization of embedding in your job, I expected to reproduce the result on cora, where different classes in cora can be separated well. Could you please show me how to achieve that?

**Comment by huunghia160799** [comment]
I think that such visualization can be done with t-SNE because that's how other papers do it.

**Comment by ines-chami** [comment]
Hi, for visualizations we used the Poincare Ball model with dimension set to 2, and then colored node embeddings based on the corresponding label class.
