### ISSUE TITLE
Availability of PPI dataset

### ISSUE THREAD

**Issue by Kaushalya** [HazyResearch/hgcn#22]
Thank you very for making the code public. Is it possible to share the PPI dataset used in the experiments?
It seems this PPI dataset is different from the PPI graphs used in previous node classification paper (e.g., GraphSAGE, GAT).

**Comment by ines-chami** [comment]
We do not plan to support inductive training as part of this repository but feel free to reach out to my co-author Rex Ying (rexying@stanford.edu) to access the inductive PPI dataset.
