### ISSUE TITLE
DATAPATH Key Error

### ISSUE THREAD

**Issue by samueledet** [HazyResearch/hgcn#3]
Hello, 

Thanks for the well written code. I cloned the repository to my  local machine, and the example on link prediction with cora dataset, but got the error below. I will appreciate your assistance in fixing this. Thank you

INFO:root:Using: cpu
INFO:root:Using seed 1234.
Traceback (most recent call last):
  File "train.py", line 153, in <module>
    train(args)
  File "train.py", line 48, in train
    data = load_data(args, os.path.join(os.environ['DATAPATH'], args.dataset))
  File "/home/samuel/Desktop/hgcn/hgcn/lib/python3.6/os.py", line 669, in __getitem__
    raise KeyError(key) from None
KeyError: 'DATAPATH'

**Comment by ines-chami** [comment]
Please run `source set_env.sh`to create environment variables before using the code.
