### ISSUE TITLE
How to train node classification for own dataset.

### ISSUE THREAD

**Issue by vigneshgig** [HazyResearch/hgcn#6]
i have csv file having node ,edges and multi- label value. how do i convert it to core dataset format.
any suggestion

Thanks,

**Comment by ines-chami** [comment]
To add a new dataset for node classification, please write a data processing function in utils/data_utils.py and add it to load_data_nc. This function should return:
- The graph adjancency matrix (scipy.csr_matrix)
- Node features (scipy.csr_matrix)
- Node labels (np.array)
