### ISSUE TITLE
what does the projection do?

### ISSUE THREAD

**Issue by ShinKyuY** [HazyResearch/hgcn#7]
Hi.
I appreciate this wonderful repository.

What role does the projection in hyperboloid.py? I understand that exp and log act as projections, but I wonder why projections are used separately. Interestingly, even if I don't use projection in hyperboloid.py of exp and log maps, I get the same performance as using projection.

Could you please tell me what the role of projection is?

**Comment by ines-chami** [comment]
Due to limited machine precision, the exp and log map might sometimes return points that are not exactly located on the manifold. Using proj and proj_tan ensures that points remain on the manifold and tangent vectors remain on the right tangent space.

**Comment by ShinKyuY** [comment]
Thank you for your reply. It really helps me
