### ISSUE TITLE
Query in the distance function

### ISSUE THREAD

**Issue by AdarshMJ** [HazyResearch/hgcn#8]
Hi! Excellent paper!

Pardon, if this seems like a silly question. Im having a hard time understanding why is there a square of the distance function? 

<img width="519" alt="Screenshot 2020-03-22 at 2 17 39 PM" src="https://user-images.githubusercontent.com/24205200/77245887-34f2e480-6c48-11ea-9876-1f6b41dfb5b3.png">

**Comment by ines-chami** [comment]
The function sqdist implements the squared hyperbolic distance. Empirically, we find that optimizing squared distances yields better performance. See Equation 14 in the paper for more details.

**Comment by ines-chami** [comment]
The function sqdist implements the squared hyperbolic distance which is numerically more stable. The non-squared distance is unstable for points that are close to each other (see Appendix C in https://arxiv.org/pdf/1804.03329.pdf for more details).
