### ISSUE TITLE
will other three datasets be released?

### ISSUE THREAD

**Issue by kourenmu** [HazyResearch/hgcn#9]
Hi
Thank you for your amazing work.
I wonder where can download other three datasets (DISEASE-M, HUMAN PPI and AIRPORT) in the paper. 

best wishes

**Comment by ines-chami** [comment]
The airport data is added to the repo. For the two other inductive datasets, please email rexying@cs.stanford.edu

**Comment by kourenmu** [comment]
thanks!

**Comment by daidaren202** [comment]
@kourenmu Hello, I am interested in these two datasets, too.  Have you gotten them? If so, can you share them with me? Thanks a lot!

**Comment by kourenmu** [comment]
> @kourenmu Hello, I am interested in these two datasets, too. Have you gotten them? If so, can you share them with me? Thanks a lot!

Hi, I didn't email rexying.
